project_name: "scoob"
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    ldflags:
      - -s -w -X github.com/Yakiyo/scoob/meta.Version={{ .Version }} -X github.com/Yakiyo/scoob/meta.BuiltAt={{ .Date }} -X github.com/Yakiyo/scoob/meta.Revision={{ .ShortCommit }}

    ignore:
      - goos: "linux"
        goarch: "arm64"
      - goos: "linux"
        goarch: "386"

archives:
  - format: binary
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
    - goos: windows
      format: binary
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  skip: true

release:
  extra_files:
    - glob: "./share/scoop/*.json"
      name_template: "scoob.json"

scoops:
  - folder: share/scoop
    commit_author:
        name: goreleaserbot
        email: bot@goreleaser.com
    commit_msg_template: "Update scoop manifest to {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://github.com/Yakiyo/scoob"
    description: "Drop-in replacement cli for scoop"
    depends: ["git"]
    repository:
      owner: "Yakiyo"
      name: "scoob"
      branch: "main"
